### PR TITLE
Dockerize the Node Scraper

### PR DESCRIPTION
**Pull request by nathanmentley**
I'm not sure if there was a need to dockerize the node scraper, but I had the dockerfile already. I wrapped it in compose like the python one to make things similar.

### CODE REVIEW

**Comment by mcsaucy** [comment]
We just changed up the entire repository structure and super-broke this PR. Can you fix the conflicts?

**Comment by nathanmentley** [comment]
Yeah, I can do that.

**Comment by OscarVanL** [comment]
I'd also like to point your attention to https://github.com/Police-Data-Accessibility-Project/Scrapers/issues/27, which we'd love your help on.

**Comment by OscarVanL** [comment]
Just tried this out and it seems to work. Nice job :)

**Pull request merged**
