### PR TITLE
Adds more scrapers

### PR DESCRIPTION
**Pull request by CaptainStabs**

### CODE REVIEW

**Comment by mcsaucy** [comment]
Typo in the file name

**Comment by CaptainStabs** [comment]
> Typo in the file name

Which one?

**Comment by CaptainStabs** [comment]
Opened the PR on the wrong branch...

**Comment by mcsaucy** [comment]
alemeda_scraper.py should be alameda_...

**Comment by CaptainStabs** [comment]
> alemeda_scraper.py should be alameda_...

Okay fixed in PR #38

**Pull request closed without merging**
