### PR TITLE
Enforce geographic sorting and naming convention

### PR DESCRIPTION
**Pull request by EvilDrPurple**
This should finish up the structure changes as part of #197

All scrapers are now sorted on the basis of `scrapers_library/COUNTY/MUNICIPALITY/SCRAPER_NAME`

I also implemented `from_root` into the scrapers as I went so that the directory changes should not break any scrapers that were not already broken.

And the `scrapers` folder has been renamed to `scrapers_library`

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
this looks solid to me, passing to @mbodeantor !

**Comment by mbodeantor** [comment]
Thanks for this, looks like a lot of work. Can you move these lines below the final import statement to keep them all together with no blank lines? Sorry, I know that's probably not a small change.
```p = from_root('CONTRIBUTING.md').parent
sys.path.insert(1, str(p))```

**Comment by EvilDrPurple** [comment]
> Thanks for this, looks like a lot of work. Can you move these lines below the final import statement to keep them all together with no blank lines? Sorry, I know that's probably not a small change.
> 
> ```
> p = from_root('CONTRIBUTING.md').parent
> sys.path.insert(1, str(p))
> ```

@mbodeantor This is actually not possible to do, it is required for the final import to work because the project path has to be put in `sys.path` to recognize where a module is being imported from. They could be moved to before all the import statements instead of in the middle, if you want that done instead.

**Comment by mbodeantor** [comment]
Ah okay, no makes sense as is then.

**Review by mbodeantor — APPROVED** [review]

**Pull request merged**
